version: "3.9"

services:
  app:
    build:
      context: .
    container_name: app_vk
    depends_on:
      - db
    networks:
      - enrollment

  db:
    container_name: db_vk
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    expose:
      - "5433"
    ports:
      - "5432:5432"
    networks:
      - enrollment
    volumes:
      - ./data/db_vk:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  enrollment:
    driver: bridge
